### ISSUE TITLE
Different times on different times of the week?

### ISSUE THREAD

**Issue by lonroe** [jamesgurung/timetable-calendar-generator#1]
This is awesome!
However, we have a split lunch, and different year groups have lunch at different times on different days. Is it possible to update the settings file to have different lesson times on different days of the week?

Thank you for allowing the world to use this!

**Comment by jamesgurung** [comment]
Hi @lonroe 

You may be able to achieve this using the current version. Say there are 5 periods per day, with different timings on Tuesdays and Thursdays (for example). Then in the settings file you should define:

- Periods 1-5 with the lesson timings for Mondays, Wednesdays and Fridays
- Periods 6-10 with the lesson timings for Tuesdays and Thursdays

Then when creating the input files, you'll need to replace, for example, 1Tue:1 with 1Tue:6 and so on. This way, The period 6-10 timings will be used instead for those days.

You may need to run the tool separately with slightly different settings for each year group, depending on exactly how things work at your school.

**Comment by lonroe** [comment]
That sounds a great idea!

Will the period labels become P6 etc? 
If yes, is it possible to use the "renames" part of the settings.json to convert P6 to P1?

If I can just get the csv files out of my MIS this looks to be awesome!

**Comment by jamesgurung** [comment]
Good point. Probably best to fork the project and edit the title declaration to:

    string title = $"P{(period - 1) % 5 + 1}. ";

This will wrap period 6 back to period 1, and so on.
