### ISSUE TITLE
Add calendar writer to edit users' Outlook Calendars

### ISSUE THREAD

**Issue by jamesgurung** [jamesgurung/timetable-calendar-generator#2]
This app can read and write users' Google Calendars directly, using a [service account](https://github.com/jamesgurung/timetable-calendar-generator/blob/master/README.md#keyjson) which is delegated domain-wide authority. The code for interfacing with the Google API is in the [Google](https://github.com/jamesgurung/timetable-calendar-generator/blob/master/src/CalendarWriters/Google) directory. The [GoogleCalendarWriter](https://github.com/jamesgurung/timetable-calendar-generator/blob/master/src/CalendarWriters/Google/GoogleCalendarWriter.cs) implements an interface with one method:

    Task WriteAsync(IList<CalendarEvent> events)

I would like to **add another calendar writer** which uses the [Microsoft Graph API](https://github.com/microsoftgraph/msgraph-sdk-dotnet) to directly edit calendars for Office 365 business customers. There doesn't seem to be any documentation for domain-wide auth, so any advice and/or pull requests would be much appreciated.

**Comment by timmy-mac** [comment]
Does this not do it?  https://docs.microsoft.com/en-gb/graph/auth-v2-service

**Comment by jamesgurung** [comment]
Feature added in 968cae1f4db7649456184bc93806a59918a7a19f.
