### ISSUE TITLE
Mock / example data

### ISSUE THREAD

**Issue by antont** [jamesgurung/timetable-calendar-generator#6]
Hi - thanks for open sourcing a nice set of software.

Would you happen to have some mock or example data at hand that could share easily?

I don't have SIMS or any other similar tool, nor any actual data yet. But am preparing a dev effort where could maybe use this code as a library for working with the scheduling and room management for whole schools.

**Comment by jamesgurung** [comment]
I'm afraid I don't have any example data. If you download the zip file from the Releases page, there are template input files included to show you what format to use. So it should be possible to mock something up if needed.

Glad the project can be of use!

**Comment by antont** [comment]
Right, I actually downloaded the zip before asking and checked the templates there, just got a bit confused when trying to figure out how to generate sensible example data so looked and asked further.

I may get a set of real data from a school tomorrow morning, but if that fails, I may attempt that generating somehow.

Thanks for info!
