### ISSUE TITLE
Change calendar name option

### ISSUE THREAD

**Issue by markdw23** [jamesgurung/timetable-calendar-generator#8]
Would it be possible to add a choose calendar name option rather than just "My timetable" or using the "Primary". This would be useful for us as we have Admin account with 5 different calendars which is used for room timetables. So for example we have Room 10, Room 11 classroom calendar.

Many thanks =D

**Comment by jamesgurung** [comment]
Hello! This sounds like an unusual use case, so I recommend forking the project. The calendar name is set here, and you can customise it as you wish:

https://github.com/jamesgurung/timetable-calendar-generator/blob/802b641bca0c0b1fc74b13bccf962c7070206f42/src/CalendarWriters/Google/GoogleCalendarWriter.cs#L15

Typically administrators set up bookable rooms as [Resources](https://support.google.com/a/answer/1034381?hl=en), which have their own calendars. I'm not sure if this is what you've done, or if you've taken a different approach?
